version: '3.9'

services:
  postgres:
    container_name: gnosis-siwe-db
    image: postgres:14-alpine
    restart: always
    ports:
      - 5439:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=dev
volumes:
  postgres_data:
